snakebot_v1:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers
  joint_1_position_controller:
    type: position_controllers/JointPositionController
    joint: rod_one_joint
    pid: {p: 0.1, i: 0.05, d: 0.01}

  joint_2_position_controller:
    type: position_controllers/JointPositionController
    joint: rod_two_joint
    pid: {p: 0.1, i: 0.05, d: 0.01}
  
  joint_3_position_controller:
    type: position_controllers/JointPositionController
    joint: rod_three_joint
    pid: {p: 0.1, i: 0.05, d: 0.01}
  
  joint_4_position_controller:
    type: position_controllers/JointPositionController
    joint: rod_four_joint
    pid: {p: 0.1, i: 0.05, d: 0.01}

  joint_5_position_controller:
    type: position_controllers/JointPositionController
    joint: rod_five_joint
    pid: {p: 0.1, i: 0.05, d: 0.01}

  joint_6_position_controller:
    type: position_controllers/JointPositionController
    joint: rod_six_joint
    pid: {p: 0.1, i: 0.05, d: 0.01}